security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
  providers:
    app_user_provider:
      mongodb:
        class: App\Document\User
        property: id
    all_users:
      chain:
        providers:
          - app_user_provider
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    login:
      pattern: ^/api/login
      stateless: true
      custom_authenticators:
          - App\Security\ApiSecretLoginAuthenticator

    api:
      pattern: ^/api
      stateless: true
      provider: app_user_provider
      jwt: ~
      custom_authenticators:
          - App\Security\OauthSuperAdminAuthenticator

  access_control:
    - { path: ^/api/login, roles: PUBLIC_ACCESS }
    - { path: ^/api/graphql, roles: ROLE_USER }
    - { path: ^/api, roles: ROLE_SUPER_ADMIN }
    - { path: ^/oauth, roles: PUBLIC_ACCESS }
    - { path: ^/api/token/refresh, roles: PUBLIC_ACCESS }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
